# Site settings
baseurl: ""
# Using a protocol-relative URL to support both HTTP and HTTPS
url: "//kneeraj.dev"

# You can uncomment and modify the following line once HTTPS is confirmed to be working
# url: "https://kneeraj.dev"

# Other Jekyll settings can be added here as needed

title: The Prompt Gallery
email: kn.neeraj.2809@gmail.com
description: >-
  The Prompt Gallery Chrome extension helps you manage and use your favorite prompts
  for AI chatbots like ChatGPT and Claude.

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Custom variables
github_username: kn-neeraj
product_name: The Prompt Gallery

# Footer links
footer_links:
  product:
    - name: Video Tour
      url: /#
    - name: Try Now
      url: /#
  company:
    - name: Privacy Policy
      url: /privacy-policy
  connect:
    email: kn.neeraj.2809@gmail.com